# WhatATheme
# local usage: bundle exec jekyll s
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ruoyue Shen
# Description of the Site
description: いつか待ってれば、いいことあるかもよ。
# A portfolio of me
# URL of Image of the Site
# site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
# site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/sea3.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ruoyueshen@ks.c.titech.ac.jp
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
linkedin_username: ruoyue-shen-2400a3188
github_username:  Alchemistyui
# youtube_channel_id: /
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Ruoyue Shen
# URL for the Image of the Author
author-image: /assets/images/IMG_4703.jpg
# 60 Words About the Author
author-about: I am a doctoral student at Tokyo Institute of Technology. My primary research interests are vision-language multi-modal modeling and video understanding. I recieve my M.S. degree in Computer Science from Tokyo Institute of Technology, Japan, in 2022. I received my bachelor's degree in Software Engineering from The University of Electronic Science and Technology of China (UESTC) in 2020.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Alchemistyui

# SASS
# sass:
#   sass_dir: _sass
#   style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
